### ISSUE TITLE
QR code not displaying in Brave Browser

### ISSUE THREAD

**Issue by dteiml** [gnosis/safe-browser-extension#80]
## Description

In Brave, the extension can be downloaded and opened. But at the step of the QR code, the QR code is missing (see Slack for screenshot).

## Environment

- Safe browser extension version: Not sure where I can find that. But I just installed the latest one from Chrome Web Store, and the current version there is 0.6.1.
- Browser version: Version 0.56.14 Chromium: 70.0.3538.102 (Official Build) (64-bit)
- Operating system: MacOS Mojave (10.14.1)

**Comment by seichris** [comment]
Still does not work.

**Comment by dangerbird** [comment]
Still not working

**Comment by germartinez** [comment]
@dteiml @seichris @dangerbird 
As you can see on this issue https://github.com/brave/brave-browser/issues/2143, Brave browser does not support Firebase Cloud Messaging.
The QR code in the Safe extension in not displayed in Brave because it tries to get the token from Firebase, but it is never received.
