### ISSUE TITLE
EIP1102 support

### ISSUE THREAD

**Issue by tschubotz** [gnosis/safe-browser-extension#91]
## Story
As a user, I need to first approve a website before a dapp can access my wallet data in order to prevent unauthorized websites from phishing and spoofing attempts.

## Background / reasoning
* [EIP1102](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md) specifies that account info should only be revealed to dapps once the user approves.
* The Safe already has a whitelisting feature. A user has to manually whitelist a page before the browser extension injects data into the web page.
* We should not require the user to first hit the Safe whitelisting-toggle before they have to additionally approve a page. This would make the current flow even more complicated. We should try to prevent that.
* We specifically introduced our kind of whitelisting, so the dapp would not know at all that the Safe is installed. This decision was made due to security concerns.

## Task
* Let's keep the current whitelisting logic.
* Once the user has whitelisted a page, auto-approve the website's EIP1102-access-request. So the user would not need to additionally approve it as well.

cc @germartinez @rmeissner @biocom

**Comment by rmeissner** [comment]
Hey @samparsky 

We are happy to see your participation in this project. @germartinez is our primary developer on this project and coordinates all work on it. 

Just as a short summary: For this issue we are actually not planning to do any changes to the UI. We will add support for for injecting our provider into the global `ethereum` variable and add the method `enable` that will actually always directly return `true`, since our whitelisting is handled prior to injection.

**Comment by germartinez** [comment]
Implemented here: https://github.com/gnosis/safe-browser-extension/pull/93
